GET http://localhost:5035/games

###
GET http://localhost:5035/games/e339aff9-7fd4-4639-93ae-f19031bd6d30

###
POST http://localhost:5035/games
Content-Type: application/json

{
    "name": "Minecraft 500",
    "genreId": "8B98431D-6518-40A4-8329-0241A63660CE",
    "price": 8.95,
    "releaseDate": "2025-10-18",
    "description": "Juego creado en Febrero-2026"
}

###
PUT http://localhost:5035/games/22E1E8D4-8B96-494A-B11E-6AFEE9CF21DA
Content-Type: application/json

{
    "name": "Stree Fighter II Turbo",
    "genreId": "AC3DA7B6-1656-4C1D-B0DB-D5B0BE51450F",
    "price": 88.50,
    "releaseDate": "1992-07-15",
    "description": "Lo modifique Yo. Street Fighter 2, the most iconic fighting game of all time, is back on the Nintendo Switch! The newest iteration of SFII in nearly 10 years, Ultra Street Fighter 2 features all of the classic characters, a host of new single player and multiplayer features, as well as two new fighters: Evil Ryu and Violent Ken!"
}

###
DELETE http://localhost:5035/games/a5048bce-a9cc-472c-91db-561f4e29fcec

###
GET http://localhost:5035/genres

