GET http://localhost:5035/games

###
GET http://localhost:5035/games/4d9185ab-0614-4f6a-bd82-dc4c352b937e

### 
POST http://localhost:5035/games
Content-Type: application/json

{
    "name": "",
    "genre": "AdventureAdventureAdventureAdventureAdventureAdventure",
    "price": -39.99,
    "releaseDate": "2024-01-15"
}
 
 ### 
 PUT http://localhost:5035/games/c2a1fc2c-bbe6-47ca-a4c3-5aa1050b1faf
Content-Type: application/json

{
    "name": "Updated Game Name",
    "genre": "Action",
    "price": 49.99,
    "releaseDate": "2024-02-20"
}

