GET http://localhost:5035/games

###
GET http://localhost:5035/games/879c318a-c42a-45a2-b564-40302d2422ef

###
POST http://localhost:5035/games
Content-Type: application/json

{
    "name": "Minecraft 400",
    "genreId": "36A80D10-0194-4CB7-A6D3-5DC0927E4E2B",
    "price": 19.99,
    "releaseDate": "2011-11-18",
    "description": "Juengo en Febrero Otro Juego!"
}

###
PUT http://localhost:5035/games/a5048bce-a9cc-472c-91db-561f4e29fcec
Content-Type: application/json

{
    "name": "Stree Fighter II Turbo",
    "genreId": "4e179397-c3f1-45ec-a271-c26f07ff64f3",
    "price": 99.99,
    "releaseDate": "1992-07-15",
    "description": "Street Fighter 2, the most iconic fighting game of all time, is back on the Nintendo Switch! The newest iteration of SFII in nearly 10 years, Ultra Street Fighter 2 features all of the classic characters, a host of new single player and multiplayer features, as well as two new fighters: Evil Ryu and Violent Ken!"
}

###
DELETE http://localhost:5035/games/a5048bce-a9cc-472c-91db-561f4e29fcec

###
GET http://localhost:5035/genres

